name: Integration tests
on: 
  pull_request:
  push:
    branches: [ master ]

jobs:
  integration_tests:
    name: Integration tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Cache SwiftPM
        uses: actions/cache@v2
        with:
          path: |
           .build/checkouts
           .build/repositories
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Install bats
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install bats
      - name: Uninstall utica
        run: make uninstall
      - name: Build and Install utica
        run: make install
      - name: Run Integration tests
        run: bats IntegrationTests
